import type { Metadata } from 'next'
import Link from 'next/link'
import { DeficitCalculator } from '@/components/calculators/deficit-calculator'
import { ToolCard } from '@/components/tools/tool-card'
import { getRelatedTools, getTool, toolPath } from '@/lib/tools/registry'
import { siteConfig } from '@/lib/site'

const tool = getTool('calculadora-deficit-calorico')
export const metadata: Metadata = { title: tool.seo.title, description: tool.seo.description, alternates: { canonical: `${siteConfig.url}${toolPath(tool.slug)}` }, openGraph: { title: tool.seo.title, description: tool.seo.description, url: `${siteConfig.url}${toolPath(tool.slug)}`, type: 'article', locale: siteConfig.locale } }
export default function DeficitPage() { const relatedTools = getRelatedTools(tool); return <div className="mx-auto flex w-full max-w-6xl flex-col gap-12 px-4 py-8 sm:px-6 lg:py-12"><nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/" className="hover:text-foreground">Início</Link></li><li aria-hidden="true">/</li><li><Link href="/ferramentas/" className="hover:text-foreground">Ferramentas</Link></li><li aria-hidden="true">/</li><li aria-current="page" className="text-foreground">Déficit calórico</li></ol></nav><header className="flex max-w-3xl flex-col gap-4"><p className="text-sm font-semibold tracking-wide text-primary uppercase">Calorias e emagrecimento</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Calculadora de Déficit Calórico</h1><p className="text-lg leading-relaxed text-muted-foreground">Estime uma meta diária de calorias para reduzir o peso de forma gradual, usando seu gasto de manutenção como referência.</p></header><section aria-labelledby="calculadora-heading" className="flex flex-col gap-6"><div><h2 id="calculadora-heading" className="text-2xl font-bold tracking-tight">Calcule seu déficit</h2><p className="mt-2 text-muted-foreground">Preencha os dados e escolha o ritmo desejado.</p></div><DeficitCalculator /></section><article className="prose prose-slate max-w-3xl dark:prose-invert"><h2>O que é déficit calórico?</h2><p>É a diferença entre as calorias gastas pelo corpo e as calorias consumidas. Um déficit moderado pode apoiar a perda de peso ao longo do tempo.</p><h2>Como o cálculo é feito?</h2><p>A calculadora usa o TDEE estimado e aplica o percentual correspondente ao ritmo escolhido. O resultado é uma meta diária aproximada, não uma prescrição.</p><h2>Como interpretar</h2><p>Use a meta como ponto de partida e acompanhe peso, medidas, fome e desempenho por algumas semanas. Ajustes pequenos são preferíveis a cortes agressivos.</p><h2>Limitações</h2><p>O gasto energético varia entre pessoas e dias. Gestantes, adolescentes e pessoas com condições de saúde devem buscar orientação profissional.</p><h2>Perguntas frequentes</h2><h3>Um déficit maior emagrece mais rápido?</h3><p>Nem sempre. Déficits muito grandes podem prejudicar adesão, recuperação e massa muscular.</p></article><section aria-labelledby="relacionadas-heading" className="flex flex-col gap-5"><div><h2 id="relacionadas-heading" className="text-2xl font-bold tracking-tight">Ferramentas relacionadas</h2><p className="mt-2 text-muted-foreground">Continue seu planejamento com outras calculadoras.</p></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{relatedTools.map((relatedTool) => <ToolCard key={relatedTool.slug} tool={relatedTool} />)}</div></section></div> }


