import type { Metadata } from 'next'
import Link from 'next/link'
import { WaterCalculator } from '@/components/calculators/water-calculator'
import { ToolCard } from '@/components/tools/tool-card'
import { getRelatedTools, getTool, toolPath } from '@/lib/tools/registry'
import { siteConfig } from '@/lib/site'
const tool = getTool('calculadora-agua')
export const metadata: Metadata = { title: tool.seo.title, description: tool.seo.description, alternates: { canonical: `${siteConfig.url}${toolPath(tool.slug)}` }, openGraph: { title: tool.seo.title, description: tool.seo.description, url: `${siteConfig.url}${toolPath(tool.slug)}`, type: 'article', locale: siteConfig.locale } }
export default function WaterPage() { const relatedTools = getRelatedTools(tool); return <div className="mx-auto flex w-full max-w-6xl flex-col gap-12 px-4 py-8 sm:px-6 lg:py-12"><nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Início</Link></li><li aria-hidden="true">/</li><li><Link href="/ferramentas/">Ferramentas</Link></li><li aria-hidden="true">/</li><li aria-current="page">Água</li></ol></nav><header className="flex max-w-3xl flex-col gap-4"><p className="text-sm font-semibold tracking-wide text-primary uppercase">Nutrição</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Calculadora de Água</h1><p className="text-lg leading-relaxed text-muted-foreground">Estime uma referência de ingestão de água considerando seu peso, exercícios e condições do dia.</p></header><section aria-labelledby="calculadora-heading" className="flex flex-col gap-6"><div><h2 id="calculadora-heading" className="text-2xl font-bold tracking-tight">Calcule sua necessidade de água</h2><p className="mt-2 text-muted-foreground">Informe seus dados para obter uma estimativa em litros.</p></div><WaterCalculator /></section><article className="prose prose-slate max-w-3xl dark:prose-invert"><h2>Como a estimativa funciona?</h2><p>O cálculo parte do peso corporal e adiciona ajustes relacionados ao tempo de exercício e ao clima informados.</p><h2>Como interpretar</h2><p>Distribua os líquidos ao longo do dia e observe sede e cor da urina. Exercícios e calor podem aumentar a necessidade.</p><h2>Limitações</h2><p>Necessidades variam conforme alimentação, suor, altitude, saúde e medicamentos. Não force o consumo excessivo de água.</p></article><section aria-labelledby="relacionadas-heading" className="flex flex-col gap-5"><h2 id="relacionadas-heading" className="text-2xl font-bold tracking-tight">Ferramentas relacionadas</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{relatedTools.map((relatedTool) => <ToolCard key={relatedTool.slug} tool={relatedTool} />)}</div></section></div> }
