import type { Metadata } from 'next'
import Link from 'next/link'
import { BodyFatCalculator } from '@/components/calculators/body-fat-calculator'
import { ToolCard } from '@/components/tools/tool-card'
import { getRelatedTools, getTool, toolPath } from '@/lib/tools/registry'
import { siteConfig } from '@/lib/site'
const tool = getTool('calculadora-percentual-gordura')
export const metadata: Metadata = { title: tool.seo.title, description: tool.seo.description, alternates: { canonical: `${siteConfig.url}${toolPath(tool.slug)}` }, openGraph: { title: tool.seo.title, description: tool.seo.description, url: `${siteConfig.url}${toolPath(tool.slug)}`, type: 'article', locale: siteConfig.locale } }
export default function BodyFatPage() { const relatedTools = getRelatedTools(tool); return <div className="mx-auto flex w-full max-w-6xl flex-col gap-12 px-4 py-8 sm:px-6 lg:py-12"><nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Início</Link></li><li aria-hidden="true">/</li><li><Link href="/ferramentas/">Ferramentas</Link></li><li aria-hidden="true">/</li><li aria-current="page">Percentual de gordura</li></ol></nav><header className="flex max-w-3xl flex-col gap-4"><p className="text-sm font-semibold tracking-wide text-primary uppercase">Composição corporal</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Calculadora de Percentual de Gordura</h1><p className="text-lg leading-relaxed text-muted-foreground">Estime seu percentual de gordura usando medidas corporais e o método da Marinha dos Estados Unidos.</p></header><section aria-labelledby="calculadora-heading" className="flex flex-col gap-6"><div><h2 id="calculadora-heading" className="text-2xl font-bold tracking-tight">Estime seu percentual</h2><p className="mt-2 text-muted-foreground">Meça as regiões indicadas com uma fita métrica.</p></div><BodyFatCalculator /></section><article className="prose prose-slate max-w-3xl dark:prose-invert"><h2>Como funciona?</h2><p>O método usa medidas de pescoço, cintura e quadril, além de altura e sexo, para estimar a proporção de gordura corporal.</p><h2>Metodologia</h2><p>A calculadora aplica as equações antropométricas da Marinha dos EUA e apresenta o resultado como percentual.</p><h2>Limitações</h2><p>Erros de medição e distribuição corporal influenciam o resultado. Para maior precisão, métodos clínicos devem ser realizados por profissionais capacitados.</p></article><section aria-labelledby="relacionadas-heading" className="flex flex-col gap-5"><h2 id="relacionadas-heading" className="text-2xl font-bold tracking-tight">Ferramentas relacionadas</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{relatedTools.map((relatedTool) => <ToolCard key={relatedTool.slug} tool={relatedTool} />)}</div></section></div> }
