import type { Metadata } from 'next'
import Link from 'next/link'
import { MacrosCalculator } from '@/components/calculators/macros-calculator'
import { ToolCard } from '@/components/tools/tool-card'
import { getRelatedTools, getTool, toolPath } from '@/lib/tools/registry'
import { siteConfig } from '@/lib/site'
const tool = getTool('calculadora-macros')
export const metadata: Metadata = { title: tool.seo.title, description: tool.seo.description, alternates: { canonical: `${siteConfig.url}${toolPath(tool.slug)}` }, openGraph: { title: tool.seo.title, description: tool.seo.description, url: `${siteConfig.url}${toolPath(tool.slug)}`, type: 'article', locale: siteConfig.locale } }
export default function MacrosPage() { const relatedTools = getRelatedTools(tool); return <div className="mx-auto flex w-full max-w-6xl flex-col gap-12 px-4 py-8 sm:px-6 lg:py-12"><nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Início</Link></li><li aria-hidden="true">/</li><li><Link href="/ferramentas/">Ferramentas</Link></li><li aria-hidden="true">/</li><li aria-current="page">Macronutrientes</li></ol></nav><header className="flex max-w-3xl flex-col gap-4"><p className="text-sm font-semibold tracking-wide text-primary uppercase">Nutrição</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Calculadora de Macronutrientes</h1><p className="text-lg leading-relaxed text-muted-foreground">Distribua suas calorias entre proteínas, carboidratos e gorduras de acordo com seu objetivo.</p></header><section aria-labelledby="calculadora-heading" className="flex flex-col gap-6"><div><h2 id="calculadora-heading" className="text-2xl font-bold tracking-tight">Calcule seus macros</h2><p className="mt-2 text-muted-foreground">Informe calorias e escolha a distribuição desejada.</p></div><MacrosCalculator /></section><article className="prose prose-slate max-w-3xl dark:prose-invert"><h2>O que são macros?</h2><p>Macronutrientes são nutrientes que fornecem energia: proteínas e carboidratos têm 4 kcal por grama, enquanto gorduras têm 9 kcal.</p><h2>Metodologia</h2><p>A calculadora aplica a distribuição escolhida ao total de calorias e converte cada parcela em gramas usando esses fatores energéticos.</p><h2>Interpretação e limitações</h2><p>Os números são referências práticas. Preferências alimentares, treino, saúde e adesão devem orientar os ajustes com um profissional.</p></article><section aria-labelledby="relacionadas-heading" className="flex flex-col gap-5"><h2 id="relacionadas-heading" className="text-2xl font-bold tracking-tight">Ferramentas relacionadas</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{relatedTools.map((relatedTool) => <ToolCard key={relatedTool.slug} tool={relatedTool} />)}</div></section></div> }
