import type { Metadata } from 'next'
import Link from 'next/link'
import { OneRepMaxCalculator } from '@/components/calculators/one-rep-max-calculator'
import { ToolCard } from '@/components/tools/tool-card'
import { getRelatedTools, getTool, toolPath } from '@/lib/tools/registry'
import { siteConfig } from '@/lib/site'
const tool = getTool('calculadora-1rm')
export const metadata: Metadata = { title: tool.seo.title, description: tool.seo.description, alternates: { canonical: `${siteConfig.url}${toolPath(tool.slug)}` }, openGraph: { title: tool.seo.title, description: tool.seo.description, url: `${siteConfig.url}${toolPath(tool.slug)}`, type: 'article', locale: siteConfig.locale } }
export default function OneRepMaxPage() { const relatedTools = getRelatedTools(tool); return <div className="mx-auto flex w-full max-w-6xl flex-col gap-12 px-4 py-8 sm:px-6 lg:py-12"><nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Início</Link></li><li aria-hidden="true">/</li><li><Link href="/ferramentas/">Ferramentas</Link></li><li aria-hidden="true">/</li><li aria-current="page">1RM</li></ol></nav><header className="flex max-w-3xl flex-col gap-4"><p className="text-sm font-semibold tracking-wide text-primary uppercase">Treino de força</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Calculadora de 1RM</h1><p className="text-lg leading-relaxed text-muted-foreground">Estime sua carga máxima para uma repetição e consulte percentuais para organizar o treino.</p></header><section aria-labelledby="calculadora-heading" className="flex flex-col gap-6"><div><h2 id="calculadora-heading" className="text-2xl font-bold tracking-tight">Calcule sua repetição máxima</h2><p className="mt-2 text-muted-foreground">Informe uma carga e o número de repetições realizadas.</p></div><OneRepMaxCalculator /></section><article className="prose prose-slate max-w-3xl dark:prose-invert"><h2>O que é 1RM?</h2><p>1RM é a carga máxima estimada que uma pessoa consegue levantar uma única vez com boa técnica.</p><h2>Metodologia</h2><p>A calculadora compara as fórmulas de Epley, Brzycki e Lombardi e gera uma tabela de cargas por percentual.</p><h2>Interpretação e limitações</h2><p>O valor é uma estimativa baseada em uma série submáxima. Técnica, fadiga e experiência alteram o resultado; não teste cargas máximas sem segurança e supervisão adequada.</p></article><section aria-labelledby="relacionadas-heading" className="flex flex-col gap-5"><h2 id="relacionadas-heading" className="text-2xl font-bold tracking-tight">Ferramentas relacionadas</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{relatedTools.map((relatedTool) => <ToolCard key={relatedTool.slug} tool={relatedTool} />)}</div></section></div> }
