import type { Metadata } from 'next'
import Link from 'next/link'
import { BmiCalculator } from '@/components/calculators/bmi-calculator'
import { ToolCard } from '@/components/tools/tool-card'
import { getRelatedTools, getTool, toolPath } from '@/lib/tools/registry'
import { siteConfig } from '@/lib/site'
const tool = getTool('calculadora-imc')
export const metadata: Metadata = { title: tool.seo.title, description: tool.seo.description, alternates: { canonical: `${siteConfig.url}${toolPath(tool.slug)}` }, openGraph: { title: tool.seo.title, description: tool.seo.description, url: `${siteConfig.url}${toolPath(tool.slug)}`, type: 'article', locale: siteConfig.locale } }
export default function BmiPage() { const relatedTools = getRelatedTools(tool); return <div className="mx-auto flex w-full max-w-6xl flex-col gap-12 px-4 py-8 sm:px-6 lg:py-12"><nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Início</Link></li><li aria-hidden="true">/</li><li><Link href="/ferramentas/">Ferramentas</Link></li><li aria-hidden="true">/</li><li aria-current="page">IMC</li></ol></nav><header className="flex max-w-3xl flex-col gap-4"><p className="text-sm font-semibold tracking-wide text-primary uppercase">Composição corporal</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Calculadora de IMC</h1><p className="text-lg leading-relaxed text-muted-foreground">Calcule seu Índice de Massa Corporal e consulte a classificação de referência da OMS.</p></header><section aria-labelledby="calculadora-heading" className="flex flex-col gap-6"><div><h2 id="calculadora-heading" className="text-2xl font-bold tracking-tight">Calcule seu IMC</h2><p className="mt-2 text-muted-foreground">Informe peso e altura para ver o resultado.</p></div><BmiCalculator /></section><article className="prose prose-slate max-w-3xl dark:prose-invert"><h2>O que é IMC?</h2><p>O Índice de Massa Corporal relaciona peso e altura em uma medida simples de triagem populacional.</p><h2>Fórmula</h2><p>O cálculo realizado é <strong>IMC = peso ÷ altura²</strong>, com peso em quilogramas e altura em metros. A classificação segue as faixas de referência da OMS.</p><h2>Interpretação e limitações</h2><p>O IMC não diferencia músculos e gordura nem mostra onde a gordura está distribuída. Interprete o resultado junto a outras medidas e ao contexto individual.</p></article><section aria-labelledby="relacionadas-heading" className="flex flex-col gap-5"><h2 id="relacionadas-heading" className="text-2xl font-bold tracking-tight">Ferramentas relacionadas</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{relatedTools.map((relatedTool) => <ToolCard key={relatedTool.slug} tool={relatedTool} />)}</div></section></div> }
