import type { Metadata } from 'next'
import Link from 'next/link'
import { PaceCalculator } from '@/components/calculators/pace-calculator'
import { ToolCard } from '@/components/tools/tool-card'
import { getRelatedTools, getTool, toolPath } from '@/lib/tools/registry'
import { siteConfig } from '@/lib/site'
const tool = getTool('calculadora-pace')
export const metadata: Metadata = { title: tool.seo.title, description: tool.seo.description, alternates: { canonical: `${siteConfig.url}${toolPath(tool.slug)}` }, openGraph: { title: tool.seo.title, description: tool.seo.description, url: `${siteConfig.url}${toolPath(tool.slug)}`, type: 'article', locale: siteConfig.locale } }
export default function PacePage() { const relatedTools = getRelatedTools(tool); return <div className="mx-auto flex w-full max-w-6xl flex-col gap-12 px-4 py-8 sm:px-6 lg:py-12"><nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Início</Link></li><li aria-hidden="true">/</li><li><Link href="/ferramentas/">Ferramentas</Link></li><li aria-hidden="true">/</li><li aria-current="page">Pace</li></ol></nav><header className="flex max-w-3xl flex-col gap-4"><p className="text-sm font-semibold tracking-wide text-primary uppercase">Corrida</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Calculadora de Pace</h1><p className="text-lg leading-relaxed text-muted-foreground">Calcule seu ritmo por quilômetro, velocidade média e tempos de prova para diferentes distâncias.</p></header><section aria-labelledby="calculadora-heading" className="flex flex-col gap-6"><div><h2 id="calculadora-heading" className="text-2xl font-bold tracking-tight">Calcule seu pace</h2><p className="mt-2 text-muted-foreground">Escolha os dados que você já conhece.</p></div><PaceCalculator /></section><article className="prose prose-slate max-w-3xl dark:prose-invert"><h2>O que é pace?</h2><p>Pace é o tempo médio necessário para percorrer um quilômetro, normalmente apresentado em minutos por quilômetro.</p><h2>Como o cálculo é feito?</h2><p>A calculadora relaciona distância, tempo e velocidade: pace é o tempo dividido pela distância, e a velocidade média é a distância dividida pelo tempo.</p><h2>Interpretação e limitações</h2><p>Use o resultado como referência para planejamento. Terreno, altimetria, vento, clima e fadiga podem mudar o ritmo real durante a prova.</p></article><section aria-labelledby="relacionadas-heading" className="flex flex-col gap-5"><h2 id="relacionadas-heading" className="text-2xl font-bold tracking-tight">Ferramentas relacionadas</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{relatedTools.map((relatedTool) => <ToolCard key={relatedTool.slug} tool={relatedTool} />)}</div></section></div> }
