import type { Metadata } from 'next'
import Link from 'next/link'
import { IdealWeightCalculator } from '@/components/calculators/ideal-weight-calculator'
import { ToolCard } from '@/components/tools/tool-card'
import { getRelatedTools, getTool, toolPath } from '@/lib/tools/registry'
import { siteConfig } from '@/lib/site'
const tool = getTool('calculadora-peso-ideal')
export const metadata: Metadata = { title: tool.seo.title, description: tool.seo.description, alternates: { canonical: `${siteConfig.url}${toolPath(tool.slug)}` }, openGraph: { title: tool.seo.title, description: tool.seo.description, url: `${siteConfig.url}${toolPath(tool.slug)}`, type: 'article', locale: siteConfig.locale } }
export default function IdealWeightPage() { const relatedTools = getRelatedTools(tool); return <div className="mx-auto flex w-full max-w-6xl flex-col gap-12 px-4 py-8 sm:px-6 lg:py-12"><nav aria-label="Breadcrumb" className="text-sm text-muted-foreground"><ol className="flex flex-wrap items-center gap-2"><li><Link href="/">Início</Link></li><li aria-hidden="true">/</li><li><Link href="/ferramentas/">Ferramentas</Link></li><li aria-hidden="true">/</li><li aria-current="page">Peso ideal</li></ol></nav><header className="flex max-w-3xl flex-col gap-4"><p className="text-sm font-semibold tracking-wide text-primary uppercase">Calorias e emagrecimento</p><h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Calculadora de Peso Ideal</h1><p className="text-lg leading-relaxed text-muted-foreground">Compare diferentes referências de peso para sua altura e veja uma faixa baseada no IMC.</p></header><section aria-labelledby="calculadora-heading" className="flex flex-col gap-6"><div><h2 id="calculadora-heading" className="text-2xl font-bold tracking-tight">Calcule seu peso de referência</h2><p className="mt-2 text-muted-foreground">Informe sua altura e seus dados básicos.</p></div><IdealWeightCalculator /></section><article className="prose prose-slate max-w-3xl dark:prose-invert"><h2>O que significa peso ideal?</h2><p>Não existe um único peso ideal para todas as pessoas. A ferramenta apresenta referências matemáticas para ajudar na interpretação da sua altura.</p><h2>Metodologia</h2><p>São comparadas as fórmulas de Devine, Robinson, Miller e Hamwi, além da faixa de IMC entre 18,5 e 24,9.</p><h2>Interpretação e limitações</h2><p>Use os valores como referências, não como meta obrigatória. IMC e fórmulas de altura não consideram composição corporal, distribuição de gordura, idade ou histórico clínico.</p><h2>Perguntas frequentes</h2><h3>O peso ideal é igual para qualquer pessoa?</h3><p>Não. O resultado depende de composição corporal, contexto e objetivos individuais.</p></article><section aria-labelledby="relacionadas-heading" className="flex flex-col gap-5"><h2 id="relacionadas-heading" className="text-2xl font-bold tracking-tight">Ferramentas relacionadas</h2><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{relatedTools.map((relatedTool) => <ToolCard key={relatedTool.slug} tool={relatedTool} />)}</div></section></div> }
